www/config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'

Rails.application.routes.draw do

  get '/health_check' => 'health_check#index'
  get '/faq'  => 'visitors#faq'
  get '/terms'  => 'visitors#terms'
  get '/unsubscribe'  => 'visitors#unsubscribe'

  devise_for :users, :controllers => { :confirmations => 'confirmations', :registrations => 'registrations', :passwords => 'passwords', sessions: 'sessions', omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end

  mount Koudoku::Engine, at: 'koudoku'
  scope module: 'koudoku' do
    get 'pricing' => 'subscriptions#index', as: 'pricing' # , constraints: { protocol: 'https' }
  end

  as :user do
    get 'user/password/new', :to => 'devise/passwords#new'
    patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
    get 'users/profile', :to => 'devise/registrations#edit', :as => :user_root
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    get '/register'  =>  'devise/registrations#new'
    get '/crm'  =>  'dashboard#crm'
    get '/crm/leads'  =>  'dashboard#leads'
    get '/crm/accounts'  =>  'dashboard#accounts'
    get '/crm/contacts'  =>  'dashboard#contacts'
    get '/crm/tasks'  =>  'dashboard#tasks'
    get '/marketing/campaigns'  =>  'dashboard#marketing_campaigns'
    get '/marketing/reports'  =>  'dashboard#marketing_reports'
    get '/marketing/templates'  =>  'dashboard#marketing_templates'
    get '/crm/opportunities'  =>  'dashboard#opportunities'
    get '/crm/profile'  =>  'dashboard#profile'
    get '/help'  =>  'dashboard#helpdesk'

    get '/crm/campaigns'  =>  'dashboard#campaigns'
    resources :websites
    resources :websites do
      collection { post :import }
    end

    resources :email_leads
    resources :social_leads
    resources :phone_leads
    resources :companies
    resources :people

    post '/dashboard' => 'dashboard#import', :as => :import_websites_path

    get '/email_leads/remove/:id'  => 'email_leads#delete', :as => :remove_email_lead_path
    get '/phone_leads/remove/:id'  => 'phone_leads#delete', :as => :remove_phone_lead_path
    get '/social_leads/remove/:id'  => 'social_leads#delete', :as => :remove_social_lead_path

    get '/email_leads/add/:id'  => 'email_leads#add', :as => :add_email_lead_path
    get '/phone_leads/add/:id'  => 'phone_leads#add', :as => :add_phone_lead_path
    get '/social_leads/add/:id'  => 'social_leads#add', :as => :add_social_lead_path

    get '/dashboard'  => 'dashboard#index', :as => :signed_in_root_path
    get '/search'  => 'dashboard#index', :as => :search_path
    post '/targets' => 'dashboard#create_target', :as => :targets_path
    get '/analytics'  => 'dashboard#analytics', :as => :analyics_path

    get '/stats' => 'events#stats'
    get '/batch' => 'events#batch'
    get '/progress' => 'events#progress'

  end

  if Rails.env.production?
  constraints subdomain: 'api' do

    post '/text/sentiment' =>  'text#sentiment'
    post '/text/nlp' =>  'text#nlp'
    post '/text/chat' =>  'text#chat'
    post '/text/analyze' =>  'text#analyze'
    post '/text/summarize' =>  'text#summarize'
    get '/website/locate' =>  'geoip#locate'
    post '/face/find' =>  'face#find'
    post '/face/rank' =>  'face#rank'
    post '/face/add' =>  'face#add'
    post '/face/identify' =>  'face#identify'
    post '/image/add' =>  'image#add'
    post '/image/delete' =>  'image#delete'
    post '/image/list' =>  'image#list'
    post '/image/ping' =>  'image#ping'
    post '/image/detect' =>  'image#detect'
    post '/image/ocr' =>  'image#ocr'

    scope module: 'api' do
      namespace :v1 do
        resources :people
        resources :companies
        resources :websites
        resources :email_leads
        resources :social_leads
        resources :phone_leads
        resources :workers
        post '/ner' =>  'workers#extract_entities'
        post '/text' =>  'workers#analyze_text'
        post '/validate' =>  'workers#validate_email'
        post '/email' =>  'workers#analyze_email'
        post '/phone' =>  'workers#analyze_phone'
        post '/name' =>  'workers#analyze_name'
        post '/product' =>  'workers#extract_product'
        post '/domain' =>  'workers#analyze_domain'
        post '/profile' =>  'workers#social_shares'
        post '/add' =>  'workers#add_image'
        post '/ocr' =>  'workers#ocr_image'
        post '/compare' =>  'workers#compare_image'
        post '/search' =>  'workers#search_image'
        post '/delete' =>  'workers#delete_image'
        post '/predict' =>  'workers#predict_image'
        post '/train' =>  'workers#train_image'
        post '/gender' =>  'workers#predict_gender'
        post '/age' =>  'workers#predict_age'
      end
    end


  end

  else
    post '/text/sentiment' =>  'text#sentiment'
    post '/text/nlp' =>  'text#nlp'
    post '/text/chat' =>  'text#chat'
    post '/text/analyze' =>  'text#analyze'
    post '/text/summarize' =>  'text#summarize'
    get '/website/locate' =>  'geoip#locate'
    post '/face/find' =>  'face#find'
    post '/face/rank' =>  'face#rank'
    post '/face/add' =>  'face#add'
    post '/face/identify' =>  'face#identify'
    post '/image/add' =>  'image#add'
    post '/image/delete' =>  'image#delete'
    post '/image/list' =>  'image#list'
    post '/image/ping' =>  'image#ping'
    post '/image/detect' =>  'image#detect'
    post '/image/ocr' =>  'image#ocr'

    scope module: 'api' do
      namespace :v1 do
        resources :people
        resources :companies
        resources :websites
        resources :email_leads
        resources :social_leads
        resources :phone_leads
        resources :workers
        post '/ner' =>  'workers#extract_entities'
        post '/text' =>  'workers#analyze_text'
        post '/validate' =>  'workers#validate_email'
        post '/email' =>  'workers#analyze_email'
        post '/phone' =>  'workers#analyze_phone'
        post '/name' =>  'workers#analyze_name'
        post '/product' =>  'workers#extract_product'
        post '/domain' =>  'workers#analyze_domain'
        post '/profile' =>  'workers#social_shares'
        post '/add' =>  'workers#add_image'
        post '/ocr' =>  'workers#ocr_image'
        post '/compare' =>  'workers#compare_image'
        post '/search' =>  'workers#search_image'
        post '/delete' =>  'workers#delete_image'
        post '/predict' =>  'workers#predict_image'
        post '/train' =>  'workers#train_image'
        post '/gender' =>  'workers#predict_gender'
        post '/age' =>  'workers#predict_age'
      end
    end
  end



  authenticate :user, -> (user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'visitors#index'

 end

www/app/views/marketing/views/admin/delete.html.erb
<% @page_title = "Delete User" %>
<%= link_to("<< Back to List", {:action => 'list'}, :class => 'back-link') %>

<div class="User delete">
  <h2>Delete User</h2>
  
  <%= form_for(:user, :url => {:action => 'destroy', :id => @user.id}) do |f| -%>

    <p>Are you sure you want to permanently delete this User?</p>
    
    <table summary="User detail view">
      <tr>
        <th>Name</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>Username</th>
        <td><%= @user.username %></td>
      </tr>
      <tr>
        <th>Created</th>
        <td><%= @user.created_at %></td>
      </tr>
      <tr>
        <th>Updated</th>
        <td><%= @user.updated_at %></td>
      </tr>
    </table>
  
    <div class="form-buttons">
      <%= submit_tag("Delete User", :method => :post) %>
    </div>
    
  <% end %>
</div>

www/app/views/marketing/views/admin/global_settings.html.erb
<% @page_title = "Global Settings" %>

<%= error_messages_for(@global_settings) %>

<div class="global_settings">
  <h2>Global Settings</h2>

  <%= form_for(:global_settings, :url => {:action => 'update_global_settings'}) do |f| %>

  <table class="table borderless" summary="Global Settings fields">
    <tr>
      <th>Application Site URL</th>
      <td><span class="ui-icon ui-icon-help" title='Full Site url including HTTP(S) protocol that will be used as the base callback url for tracking  details from visitors'></span></td>
      <td><%= f.text_field(:site_url, placeholder: 'https://your-server.net',
                    required: true, class: 'form-control') %></td>
    </tr>
    <tr>
    <tr>
      <th>Apache Restart Command</th>
      <td><span class="ui-icon ui-icon-help" title='Command used on the Operating System to restart Apache. This is required to manage the virtual hosts for websites'></span></td>
      <td><%= f.text_field(:command_apache_restart, class: 'form-control') %></td>
    </tr>
    <tr>
      <th>Apache Status Command</th>
      <td><span class="ui-icon ui-icon-help" title='Command used on the Operating System to status Apache. This is required for monitoring the web server.'></span></td>
      <td><%= f.text_field(:command_apache_status, class: 'form-control') %></td>
    </tr>
    <tr>
      <th>Apache VHOST Command</th>
      <td><span class="ui-icon ui-icon-help" title='Command used on the Operating System for listing all Virtual Hosts.'></span></td>
      <td><%= f.text_field(:command_apache_vhosts, class: 'form-control') %></td>
    </tr>
    <tr>
      <th>Apache sites-enabled Path</th>
      <td>
        <span class="ui-icon ui-icon-help" title='Path or location of where the Apache stores the sites-enabled virtual hosts'></span></td>
      <td><%= f.text_field(:sites_enabled_path, class: 'form-control') %></td>
    </tr>
    <tr>
      <th>Reports Refresh Time</th>
      <td><span class="ui-icon ui-icon-help" title='Time in seconds use to poll the server for stats on the campaign stats page'></span></td>
      <td><%= f.text_field(:reports_refresh, class: 'form-control') %></td>
    </tr>
    <tr>
      <th>SMTP Timeout</th>
      <td><span class="ui-icon ui-icon-help" title='Timeout in seconds to allow when sending emails through the SMTP server'></span></td>
      <td><%= f.text_field(:smtp_timeout, class: 'form-control') %></td>
    </tr>
    <tr>
      <th>BeEF URL</th>
      <td><span class="ui-icon ui-icon-help" title='URL used for BeEF to hook browsers with javascript'></span></td>
      <td><%= f.text_field(:beef_url,
                placeholder: "http://your-server.net/hook.js",
                class: 'form-control') %></td>
    </tr>
    <tr>
      <th>Bing API Key</th>
      <td>
        <span class="ui-icon ui-icon-help" title='Bing API Key required for email enumeration'></span>
      </td>
      <td>
        <%= f.text_field(:bing_api, 
                placeholder: "BKqC2hIKr8foem2E1qiRvB5ttBQJK8objH8kZE/WJVs=", 
                class: 'form-control') %>
      </td>
    </tr>
    <tr>
      <th>Background Email</th>
      <td><span class="ui-icon ui-icon-help" title='Use Sidekiq to send emails in the background'></span></td>
      <td><%= f.check_box(:asynchronous) %></td>
    </tr>
  </table>

  <%= submit_tag("Update Changes", class: 'btn btn-primary') %>

  <% end %>

</div>

www/app/views/marketing/views/admin/list.html.erb
<% @page_title = "Users" %>

<div class="page-header">
  <h2>Your Registration</h2>
</div>

<div class="User list">
  <%= link_to('Manage Account', edit_user_registration_path(current_user), class: 'btn btn-default') %>
  <h2>Users</h2>

  <% if params[:approved] == "false" %>
      <%= link_to "All Users", :action => "list" %>
  <% else %>
      <%= link_to "Users awaiting approval", :action => "list", :approved => "false" %>
  <% end %>

  <div><%= pluralize(@users.size, 'user') %> found</div>
  <table class="table table-condensed table-hover">
    <thead>
      <tr>
        <th>&nbsp;</th>
        <th>Name</th>
        <th>Username</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag('manager.png', size: '35x35') %></td>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td class="actions">
          <% if user.approved? %>
              <%= link_to "Revoke", revoke_user_path(user), method: :post, class: 'btn btn-default btn-xs' %>
          <% else %>
              <%= link_to "Approve", approve_user_path(user), method: :post, class: 'btn btn-default btn-xs' %>
          <% end %>
          <%=  link_to "Logins", logins_user_path(user), class: 'btn btn-default btn-xs' %>
          <%= link_to "Delete", user_path(user), method: :delete, data: {confirm: 'Are you sure you want to permanently delete this user?'}, class: 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

www/app/views/marketing/views/admin/logins.html.erb
<% @page_title = "#{@user.name} Login Archive" %>
<%= link_to("<< Back to Users Menu", list_user_index_path, :class => 'back-link') %>
<div class="User list">
  <h2><%=  @user.name %> Logins</h2>

  <div><%= pluralize(@logins.size, 'login') %> logged out of <%= @user.sign_in_count %> logins total </div>
  <table class="table table-striped" summary="Campaign list">
    <tr class="header">
      <th>Date</th>
      <th>IP</th>
    </tr>

    <% @logins.each do |login| %>

        <tr>
          <td><%= login.current_sign_in_at %></td>
          <td><%= login.current_sign_in_ip %></td>
        </tr>
    <% end %>
  </table>

</div>